### ISSUE TITLE
remove `f(x) -> x * 2` function definition syntax

### ISSUE THREAD

**Issue by bmintz** [DXsmiley/mathbot#24]
![](https://cdn.discordapp.com/attachments/325908974648164352/416133942119366666/unknown.png)

**Comment by bmintz** [comment]
thanks fam :heart:

**Comment by sayaks** [comment]
rip ;-;

**Comment by bmintz** [comment]
no u

**Comment by sayaks** [comment]
i liked it :c

**Comment by bmintz** [comment]
zen of python:
12. There should be one-- and preferably only one --obvious way to do it.

**Comment by sayaks** [comment]
`a.map(lambda x: print (x))`
```
for x in a:
    print(x)
```

**Comment by bmintz** [comment]
1. a.map isn't a thing, you want the global map
2. map is lazy, won't print unless you make a list out of it
3. if you just want side effects the right way to do it is not to make a list, and the map isn't the right way to do it.

zen of python again:
13. Although that way may not be obvious at first unless you're Dutch.

**Comment by sayaks** [comment]
so the zen of python is:
the obvious way to do it is the way we think is obvious, not what you think is obvious

**Comment by bmintz** [comment]
i mean yeah python culture is kinda dogmatic but generating a list just for side effects is pretty dumb anyway

**Comment by sayaks** [comment]
also this isn't python, this is smiley's own language

**Comment by bmintz** [comment]
that's… true

**Comment by sayaks** [comment]
being python is just an implementation detail

**Comment by UniQ0** [comment]
:thinking:

**Comment by bmintz** [comment]
yeah yeah yeah i get it
although the exact sympy stuff would be hard

**Comment by OfficialOxide** [comment]
i agree
