### ISSUE TITLE
Change status indicator to orange (idle) when a shard is restarting

### ISSUE THREAD

**Issue by DXsmiley** [DXsmiley/mathbot#27]
When one or more of the bot's shards are restarting, the status indicator should be set or orange (instead of the usual green) in order to indicate that it is temporarily down.

**Comment by DXsmiley** [comment]
This has been implemented and released but I'm watching its behavior for a while so I convince myself that it works as intended.

**Comment by Ytrog** [comment]
Any update on this?

**Comment by DXsmiley** [comment]
I'm convinced it works now. Closing the issue.
