### ISSUE TITLE
Integers with leading 0's cause an error

### ISSUE THREAD

**Issue by DXsmiley** [DXsmiley/mathbot#32]
Reproduce with: `== 01`

Floats with extra leading zeros behave as intended.

**Comment by sayaks** [comment]
this actually happens if you do `sympy.sympify("01")` as well

**Comment by DXsmiley** [comment]
`sympy.Number` throws an error, but `sympy.Integer` doesn't.

The solution is probably to just strip leading zeros from the string before passing it to `sympy.Number` (and also checking for the case where the number *is* zero).
