### ISSUE TITLE
Edit First Function Exercise doesn't allow second function

### ISSUE THREAD

**Issue by awjdthornton** [DXsmiley/mathbot#40]
Exercise 5: Edit First Function doesn't allow me to add the Walk step next to the rocket in the picture. I am using Chrome (Version 67.0.3396.99 (Official Build) (64-bit)) on a Windows 10 machine.

![snag_65a6d546](https://user-images.githubusercontent.com/10272242/42834120-050beefa-89ab-11e8-8d05-56c7da3ba491.png)

**Comment by DXsmiley** [comment]
🤔

**Comment by bmintz** [comment]
![:thonk:](https://user-images.githubusercontent.com/538336/42849157-b8f56bda-89e7-11e8-93ab-7ed6970fc68e.png)
