### ISSUE TITLE
Adding physics package

### ISSUE THREAD

**Issue by PvdBerg1998** [DXsmiley/mathbot#53]
I'd understand you wouldn't want to add every random package someone suggests, so I'm going to suggest one anyway: the physics package. I use discord a lot to communicate with my fellow physics students and this package is used very often.
Here are the [docs](http://mirrors.ibiblio.org/CTAN/macros/latex/contrib/physics/physics.pdf).
I hope you'll consider adding it to your template, it would make quickly writing derivatives and such a lot easier. It would make the bot compatible with our reports, so we can just copy paste pieces back and forth.

Thanks!

**Comment by PvdBerg1998** [comment]
What do you think about this @DXsmiley?

**Comment by DXsmiley** [comment]
The physics package has been mentioned a few times now by a few different people. I've added it now 👍
