### ISSUE TITLE
complex calculations in MathBot?

### ISSUE THREAD

**Issue by letzfets** [DXsmiley/mathbot#65]
How can I do complex numbers in MathBot, like calculating the amplitude, phase, real part imaginary part of a complex number?

**Comment by DXsmiley** [comment]
Both the `=wolf` and `=calc` commands can handle complex numbers.

The bot understands complex numbers of the form `3 + 4i`, as well as the functions `abs` (to get the amplitude) and `arg` (to get the phase).

If you need further assistance on using the bot, it's best to ask on the official discord server: https://discord.gg/JbJbRZS
