### ISSUE TITLE
[BUG] Backticks in =tex are not converted to left quotes

### ISSUE THREAD

**Issue by MithicSpirit** [DXsmiley/mathbot#68]
In regular LaTeX using backticks (\`) converts them to left quotes (‘), however, this does not seem to work in the `=tex` command. Things like `=tex \text{``hello''}` seem to be equivalent to just typing `=tex \text{hello''}`. In order to insert real left quotes with `=tex` one has to use the actual unicode character for left quotes (‘) in their message. 

From some digging around I believe that it might be related to this: https://github.com/DXsmiley/mathbot/blob/c9d38e944579fea62be0ce0f3cf2bd7ee72565c8/mathbot/modules/latex/__init__.py#L233

**Comment by DXsmiley** [comment]
I've fixed this and will be deploying a patch shortly.
