### ISSUE TITLE
"5 - (2*(2))" and "5 - 2(2)"; MathBot gives different answers

### ISSUE THREAD

**Issue by sleepybraincells** [DXsmiley/mathbot#89]
MathBot gives two different answers for "5 - (2*(2))" and " 5 - 2(2)" even though they're basically the same question.
It gives "1" as the answer for "5 - (2*(2))"
and it gives "3   2" as the answer for "5 - 2(2)"

**Comment by sonataop13** [comment]
My guess would be that this is intended behaviour. MathBot's calculator has a number of features builtin that diverge into esolang territory, see `=help turing` for details.
In short, they're not the same to MathBot: one's `5-2*2` and one's `5-2, 2`. Keep multiplication to * and × only.
